pull_request_rules:
  - name: Add CI label
    conditions:
      - or:
          - "title~=^ci:"
          - "title~=^e2e:"
          - files~=.github/
          - files~=.markdownlint-config.yaml
          - files~=tests/
          - files~=e2e/
    actions:
      label:
        add:
          - ci
  - name: Add Mergify label
    conditions:
      - or:
          - "title~=^mergify:"
          - files~=.mergify.yml$
    actions:
      label:
        add:
          - mergify
  - name: Automatic merge on approval
    conditions:
      - and:
          - "-draft"
          - check-success=e2e (3.11, 1.75, bootstrap, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, bootstrap_build_tags, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, bootstrap_cache, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, bootstrap_conflicting_requirements, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, bootstrap_constraints, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, bootstrap_extras, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, bootstrap_git_url, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, bootstrap_git_url_tag, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, bootstrap_prerelease, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, bootstrap_sdist_only, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, build, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, build_order, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, build_settings, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, build_steps, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, download_sequence, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, elfdeps, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, extra_metadata, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, lint_requirements, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, meson, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, migrate_graph, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, optimize_build, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, override, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, pep517_build_sdist, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, post_bootstrap_hook, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, prebuilt_wheel_hook, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, prebuilt_wheels_alt_server, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, report_missing_dependency, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, rust_vendor, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, bootstrap, macos-latest)
          - check-success=e2e (3.12, 1.75, bootstrap, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, bootstrap_build_tags, macos-latest)
          - check-success=e2e (3.12, 1.75, bootstrap_build_tags, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, bootstrap_cache, macos-latest)
          - check-success=e2e (3.12, 1.75, bootstrap_cache, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, bootstrap_conflicting_requirements, macos-latest)
          - check-success=e2e (3.12, 1.75, bootstrap_conflicting_requirements, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, bootstrap_constraints, macos-latest)
          - check-success=e2e (3.12, 1.75, bootstrap_constraints, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, bootstrap_extras, macos-latest)
          - check-success=e2e (3.12, 1.75, bootstrap_extras, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, bootstrap_git_url, macos-latest)
          - check-success=e2e (3.12, 1.75, bootstrap_git_url, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, bootstrap_git_url_tag, macos-latest)
          - check-success=e2e (3.12, 1.75, bootstrap_git_url_tag, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, bootstrap_prerelease, macos-latest)
          - check-success=e2e (3.12, 1.75, bootstrap_prerelease, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, bootstrap_sdist_only, macos-latest)
          - check-success=e2e (3.12, 1.75, bootstrap_sdist_only, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, build, macos-latest)
          - check-success=e2e (3.12, 1.75, build, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, build_order, macos-latest)
          - check-success=e2e (3.12, 1.75, build_order, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, build_settings, macos-latest)
          - check-success=e2e (3.12, 1.75, build_settings, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, build_steps, macos-latest)
          - check-success=e2e (3.12, 1.75, build_steps, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, download_sequence, macos-latest)
          - check-success=e2e (3.12, 1.75, download_sequence, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, elfdeps, macos-latest)
          - check-success=e2e (3.12, 1.75, elfdeps, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, extra_metadata, macos-latest)
          - check-success=e2e (3.12, 1.75, extra_metadata, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, lint_requirements, macos-latest)
          - check-success=e2e (3.12, 1.75, lint_requirements, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, meson, macos-latest)
          - check-success=e2e (3.12, 1.75, meson, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, migrate_graph, macos-latest)
          - check-success=e2e (3.12, 1.75, migrate_graph, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, optimize_build, macos-latest)
          - check-success=e2e (3.12, 1.75, optimize_build, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, override, macos-latest)
          - check-success=e2e (3.12, 1.75, override, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, pep517_build_sdist, macos-latest)
          - check-success=e2e (3.12, 1.75, pep517_build_sdist, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, post_bootstrap_hook, macos-latest)
          - check-success=e2e (3.12, 1.75, post_bootstrap_hook, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, prebuilt_wheel_hook, macos-latest)
          - check-success=e2e (3.12, 1.75, prebuilt_wheel_hook, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, prebuilt_wheels_alt_server, macos-latest)
          - check-success=e2e (3.12, 1.75, prebuilt_wheels_alt_server, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, report_missing_dependency, macos-latest)
          - check-success=e2e (3.12, 1.75, report_missing_dependency, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, rust_vendor, macos-latest)
          - check-success=e2e (3.12, 1.75, rust_vendor, ubuntu-latest)

          # At least 1 reviewer
          - "#approved-reviews-by>=1"

    actions:
      merge:
        method: merge
