pull_request_rules:
  - name: Add CI label
    conditions:
      - or:
          - "title~=^hatch:"
          - "title~=^ci:"
          - "title~=^e2e:"
          - files~=pyproject.toml
          - files~=.github/
          - files~=.markdownlint-config.yaml
          - files~=tests/
          - files~=e2e/
    actions:
      label:
        add:
          - ci
  - name: Add Mergify label
    conditions:
      - or:
          - "title~=^mergify:"
          - files~=.mergify.yml$
    actions:
      label:
        add:
          - mergify
  - name: Automatic merge on approval
    conditions:
      - and:
          - "-draft"

          # Unit tests
          - check-success=unit (3.11, 1.75, ubuntu-latest)
          - check-success=unit (3.11, 1.75, macos-latest)
          - check-success=unit (3.12, 1.75, ubuntu-latest)
          - check-success=unit (3.12, 1.75, macos-latest)

          # MyPy type checking
          - check-success=mypy

          # E2E test suites (consolidated from individual tests)
          - check-success=e2e (3.11, 1.75, ci_bootstrap_parallel_suite, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, ci_bootstrap_suite, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, ci_build_suite, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, ci_config_suite, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, ci_specialized_suite, ubuntu-latest)
          - check-success=e2e (3.11, 1.75, ci_workflow_suite, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, ci_bootstrap_parallel_suite, macos-latest)
          - check-success=e2e (3.12, 1.75, ci_bootstrap_parallel_suite, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, ci_bootstrap_suite, macos-latest)
          - check-success=e2e (3.12, 1.75, ci_bootstrap_suite, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, ci_build_suite, macos-latest)
          - check-success=e2e (3.12, 1.75, ci_build_suite, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, ci_config_suite, macos-latest)
          - check-success=e2e (3.12, 1.75, ci_config_suite, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, ci_specialized_suite, macos-latest)
          - check-success=e2e (3.12, 1.75, ci_specialized_suite, ubuntu-latest)
          - check-success=e2e (3.12, 1.75, ci_workflow_suite, macos-latest)
          - check-success=e2e (3.12, 1.75, ci_workflow_suite, ubuntu-latest)

          # At least 1 reviewer from maintainers
          - and:
            - "#approved-reviews-by>=1"

    actions:
      merge:
        method: merge
