"""Package settings for Fromager build system."""

from ._hooks import default_update_extra_environ, get_extra_environ
from ._models import (
    BuildOptions,
    DownloadSource,
    GitOptions,
    PackageSettings,
    ProjectOverride,
    PurlConfig,
    ResolverDist,
    SbomSettings,
    VariantInfo,
)
from ._pbi import PackageBuildInfo
from ._resolver import (
    BuildSDist,
    DownloadKind,
    GitHubTagCloneResolver,
    GitHubTagDownloadResolver,
    GitLabTagCloneResolver,
    GitLabTagDownloadResolver,
    HookPrebuiltResolver,
    HookSDistResolver,
    LegacyResolver,
    NotAvailableResolver,
    PyPIDownloadResolver,
    PyPIGitResolver,
    PyPIPrebuiltResolver,
    PyPISDistResolver,
    pep440_tag_matcher,
)
from ._settings import Settings, SettingsFile
from ._templates import substitute_template
from ._typedefs import (
    MODEL_CONFIG,
    Annotations,
    BuildDirectory,
    EnvKey,
    EnvVars,
    GlobalChangelog,
    Package,
    PackageVersion,
    PatchMap,
    RawAnnotations,
    Template,
    Variant,
    VariantChangelog,
)

__all__ = (
    "MODEL_CONFIG",
    "Annotations",
    "BuildDirectory",
    "BuildOptions",
    "BuildSDist",
    "DownloadKind",
    "DownloadSource",
    "EnvKey",
    "EnvVars",
    "GitHubTagCloneResolver",
    "GitHubTagDownloadResolver",
    "GitLabTagCloneResolver",
    "GitLabTagDownloadResolver",
    "GitOptions",
    "GlobalChangelog",
    "HookPrebuiltResolver",
    "HookSDistResolver",
    "LegacyResolver",
    "NotAvailableResolver",
    "Package",
    "PackageBuildInfo",
    "PackageSettings",
    "PackageVersion",
    "PatchMap",
    "ProjectOverride",
    "PurlConfig",
    "PyPIDownloadResolver",
    "PyPIGitResolver",
    "PyPIPrebuiltResolver",
    "PyPISDistResolver",
    "RawAnnotations",
    "ResolverDist",
    "SbomSettings",
    "Settings",
    "SettingsFile",
    "Template",
    "Variant",
    "VariantChangelog",
    "VariantInfo",
    "default_update_extra_environ",
    "get_extra_environ",
    "pep440_tag_matcher",
    "substitute_template",
)
